### PR TITLE
Add bower.json

### LINKED ISSUE #5: bower.json
Please add bower.json for browser apps.

### PR DESCRIPTION
**Pull request by mohsen1**
Fixes #5 

You should also use Bower CLI to publish this in Bower repository:

### CODE REVIEW

**Comment by papandreou** [comment]
I tagged v8.0.1, ran `npm install -g bower`, `npm login`, and then:

```
$ bower register memoizeasync git://github.com/papandreou/node-memoizeasync.git 
bower memoizeasync#*           resolve git://github.com/papandreou/node-memoizeasync.git#*
bower memoizeasync#*           ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/papandreou/node-memoizeasync.git", exit code of #128 fatal: unable to connect to github.com: github.com[0: 192.30.252.129]: errno=Connection timed out

Additional error details:
fatal: unable to connect to github.com:
github.com[0: 192.30.252.129]: errno=Connection timed out
```

What gives?

**Comment by mohsen1** [comment]
Maybe try HTTP

**Comment by mohsen1** [comment]
I just registered it for you. Since it has the author key in bower.json it is under your name.

**Comment by papandreou** [comment]
Ah, I just tried again and got a "EDUPLICATE Duplicate package" error. I guess that's why.

Thanks :). Is there anything I need to do from now on to keep the package updated in bower?

**Comment by mohsen1** [comment]
You can use mversion module to bump of versions together

**Pull request merged**
